// Generated by CoffeeScript 1.3.3
(function() {
  var Deeplink, Info, Internas, Mobile, Thumb, root;

  Deeplink = (function() {
    var chageHashFunc, defineDocument, getHashFunc, getPageFunc;

    Deeplink.doc = void 0;

    Deeplink.deppInit = void 0;

    function Deeplink(_name) {}

    Deeplink.prototype.init = function() {
      this.doc = defineDocument();
      root.Main.pageCurrent = root.Main.containersDeepLink[getPageFunc()];
      if (root.Main.pageCurrent !== "home" && root.Main.pageCurrent !== "") {
        $(".logoStrip").css("marginTop", -(72 * 14));
        return root.Main.nav.callNav("page");
      }
    };

    Deeplink.prototype.getHash = function() {
      return this.getHashFunc();
    };

    Deeplink.prototype.chageHash = function(_page) {
      return chageHashFunc(_page);
    };

    getPageFunc = function() {
      var hashTag, page;
      hashTag = getHashFunc();
      hashTag = hashTag.replace("#/", "");
      hashTag = hashTag.replace("#!/", "");
      hashTag = hashTag.replace("#!", "");
      hashTag = hashTag.replace("/", "");
      hashTag = hashTag.replace("/", "");
      if (!Array.indexOf) {
        Array.prototype.indexOf = function(obj) {
          var i;
          i = 0;
          while (i < this.length) {
            if (this[i] === obj) {
              return i;
            }
            i++;
          }
          return -1;
        };
      }
      page = root.Main.containersDeepLink.indexOf(hashTag);
      if (page < 1) {
        page = 1;
      }
      return page;
    };

    getHashFunc = function() {
      return root.Main.deepLink.doc.location.hash;
    };

    chageHashFunc = function(_page) {
      var _hash, _pageName;
      _hash = root.Main.containersDeepLink[_page];
      _pageName = _hash.replace(/[\d\.]+/g, "");
      _pageName = _hash;
      _hash = _pageName;
      return root.Main.deepLink.doc.location.hash = "#!/" + _hash;
    };

    defineDocument = function() {
      try {
        return (top.document !== undefined ? top : window);
      } catch (a) {
        return window;
      }
    };

    return Deeplink;

  })();

  Info = (function() {
    var animateArrows, callPage, createInfo, motionInit, shareInfo, typeInfo;

    function Info(name) {
      this.name = name;
      createInfo();
      typeInfo();
      shareInfo();
    }

    Info.prototype.motion = function() {
      var _temp;
      _temp = 0;
      if (root.Main.pageCurrent === "home") {
        _temp = 1;
      } else {
        _temp = 0;
      }
      return window.setTimeout((function() {
        return motionInit();
      }), 1000 * _temp);
    };

    callPage = function() {
      return root.Main.callPage();
    };

    Info.prototype.infoResize = function() {
      return typeInfo();
    };

    createInfo = function() {
      $("body").append("<div class=\"info\"></div>");
      $(".info").append("<div class=\"borda\"></div>");
      $(".info").append("<div class=\"logo\"></div>");
      $(".info").append("<div class=\"sobre\"></div>");
      $(".info").append("<div class=\"share\"></div>");
      $(".info").append("<div class=\"btn_about\">ABOUT</div>");
      $(".info .logo").append("<div class=\"logoStrip\"></div>");
      $(".info .logo .logoStrip").append("<img src=\"include/img/logo.png\" width=\"163\" height=\"2160\" alt=\"\" title=\"\" />");
      $(".info .logo").append("<div class=\"hit_logo\"></div>");
      $(".sobre").text(" Web e Game developer - com foco em e-learning ");
      $(".info .share").append("<div class=\"face\"></div>");
      $(".info .share").append("<div class=\"twitter\"></div>");
      $(".info .share").append("<div class=\"plus\"></div>");
      $(".info").css("opacity", 0);
      $(".info .sobre").css("opacity", 0.8);
      $(".info .share").css("opacity", 0.8);
      $(".info .btn_about").css("opacity", 1);
      $(".info .logo .hit_logo").css("opacity", 0);
      return $(".info .btn_about").on({
        click: function() {
          if (root.Main.pageCurrent !== "about") {
            root.Main.pageCurrent = "about";
            return callPage();
          }
        },
        mouseover: function() {
          if (root.Main.pageCurrent !== "about") {
            return $(this).css("cursor", "pointer");
          }
        },
        mouseout: function() {}
      });
    };

    typeInfo = function() {
      $(".logo").css("left", 40);
      $(".logo").css("top", 40);
      $(".sobre").css("top", parseFloat($(".logo").css("top")) + 20);
      $(".csswinnerAlpha").css("opacity", 0);
      if (root.Main.type === 1) {
        $(".info").css("width", $(window).width() * (1 - root.Main.tamPocentagem) + 100);
        $(".info").css("height", $(window).height());
        $(".info").css("left", $(window).width() * root.Main.tamPocentagem + root.Main.margemThumb);
        $(".borda").css("height", $(window).height());
        $(".borda").css("width", 16);
        $(".borda").css("background", "url(include/img/borda2.png)");
        $(".sobre").css("width", parseFloat($(".info").css("width")) - parseFloat($(".sobre").css("left")) - 100);
        $(".info .share").css("left", parseFloat($(".borda").css("width")) + 50);
        $(".info .share").css("top", $(window).height() - 100);
        $(".info .btn_about").css("top", $(window).height() - 135);
        $(".info .btn_about").css("left", 14);
        $(".csswinner").css("display", "block");
      }
      if (root.Main.type === 2) {
        $(".info").css("width", $(window).width() * (1 - root.Main.tamPocentagem) + 7);
        $(".info").css("height", $(window).height());
        $(".info").css("left", 0);
        $(".borda").css("height", $(window).height());
        $(".borda").css("width", 16);
        $(".borda").css("left", parseFloat($(".info").css("width")) - 16);
        $(".borda").css("background", "url(include/img/borda4.png)");
        $(".info .share").css("top", $(window).height() - 100);
        $(".info .share").css("left", 50);
        $(".info .btn_about").css("top", $(window).height() - 135);
        $(".csswinner").css("left", $(window).width() * (1 - root.Main.tamPocentagem) + 7);
        $(".csswinner").css("display", "block");
      }
      if (root.Main.type === 3) {
        $(".info").css("width", $(window).width());
        $(".info").css("height", $(window).height() * (1 - root.Main.tamPocentagem));
        $(".borda").css("height", 16);
        $(".borda").css("width", $(window).width());
        $(".borda").css("top", parseFloat($(".info").css("height")) - 16);
        $(".borda").css("background-image", "url(include/img/borda1.png)");
        $(".info .share").css("left", parseFloat($(".info").css("width")) - 130);
        $(".info .share").css("top", parseFloat($(".info").css("height")) - 100);
        $(".info .btn_about").css("padding-left", 5);
        $(".info .btn_about").css("padding-right", 60);
        $(".info .btn_about").css("left", parseFloat($(".info").css("width")) - 125);
        $(".info .btn_about").css("top", parseFloat($(".info").css("height")) - 135);
        $(".csswinner").css("top", parseFloat($(".info").css("height")) + 50);
        $(".csswinner").css("display", "block");
      }
      if (root.Main.type === 4) {
        $(".info").css("width", $(window).width());
        $(".info").css("height", $(window).height() * (1 - root.Main.tamPocentagem));
        $(".info").css("top", $(window).height() - parseFloat($(".info").css("height")));
        $(".borda").css("height", 16);
        $(".borda").css("width", $(window).width());
        $(".borda").css("background-image", "url(include/img/borda3.png)");
        $(".info .share").css("left", parseFloat($(".info").css("width")) - 130);
        $(".info .share").css("top", parseFloat($(".info").css("height")) - 75);
        $(".info .btn_about").css("padding-left", 5);
        $(".info .btn_about").css("padding-right", 60);
        $(".info .btn_about").css("left", parseFloat($(".info").css("width")) - 125);
        $(".info .btn_about").css("top", parseFloat($(".info").css("height")) - 110);
        return $(".csswinner").css("display", "block");
      }
      /*
      		if root.Main.type is 3 or root.Main.type is 4 and $(window).height() < 650 # VERTICAL # caso sejá menor 650 px
      		   	$(".logo").css "top",20
      		   	$(".sobre").css "top",parseFloat($(".logo").css("top"))+20
      		   	$(".info .btn_about").css "top",parseFloat($(".info").css("height")) - 110
      		   	$(".info .share").css "top",parseFloat($(".info").css("height")) - 75
      */

    };

    motionInit = function() {
      $(".csswinnerAlpha").delay(200).animate({
        opacity: 0.95
      }, 700, "easeOutSine");
      $(".info").delay(200).animate({
        opacity: 0.95
      }, 700, "easeOutSine");
      return setTimeout((function() {
        if (root.Main.pageCurrent === 'home') {
          animateArrows(".info .logo .logoStrip", 72, 14);
        }
        return $(".info .logo").css("opacity", 1);
      }), 1000 * 1);
    };

    shareInfo = function() {
      $(".share .face").append($("#shareData #shareDataFace").html());
      $(".share .twitter").append($("#shareData #shareDataTwitter").html());
      return $(".share .plus").append($("#shareData #shareDataPlus").html());
    };

    animateArrows = function(target, amount, numFrames) {
      var incr, moveImage, newPos;
      moveImage = function() {
        newPos -= incr;
        $(target).css("marginTop", newPos);
        if (newPos > -(amount * numFrames)) {
          return setTimeout(moveImage, 30);
        }
      };
      incr = amount;
      newPos = 0;
      return moveImage();
    };

    return Info;

  })();

  Internas = (function() {
    var activeLoader, addContentPage, animateArrows, contentAbout, contentInterna, createInternas, createNavControl, desactiveLoader, internaAjax, loaderImagem, motionInternas, motionReturnHome, resizeInternas, returnHomeEvent, typeInterna;

    function Internas(name) {
      this.name = name;
    }

    Internas.prototype.init = function() {};

    Internas.prototype.callInterna = function(_x_) {
      return createInternas(_x_);
    };

    Internas.prototype.navControl = function() {
      return createNavControl();
    };

    returnHomeEvent = function() {
      return root.Main.callPage("home");
    };

    Internas.prototype.internasResize = function() {
      return resizeInternas();
    };

    createInternas = function(_x_) {
      root.Main.activeX = _x_;
      if (!root.Main.activeX) {
        $(".interna").remove();
      }
      typeInterna();
      motionInternas();
      return internaAjax();
    };

    createNavControl = function() {
      $(".content").remove();
      return internaAjax();
    };

    typeInterna = function() {
      $("body").append("<div class=\"interna\"></div>");
      $(".interna").append('<div class="loader"></div>');
      $(".interna").css("opacity", 0);
      if (root.Main.type === 1) {
        $(".interna").css("height", $(window).height());
        $(".interna").css("width", $(window).width() * root.Main.tamPocentagem);
        $(".interna").css("left", root.Main.margemThumb);
      }
      if (root.Main.type === 2) {
        $(".interna").css("height", $(window).height());
        $(".interna").css("width", $(window).width() * root.Main.tamPocentagem);
        $(".interna").css("left", $(window).width() * (1 - root.Main.tamPocentagem) + 6);
      }
      if (root.Main.type === 3) {
        $(".interna").css("height", $(window).height() - parseFloat($(".info").css("height")));
        $(".interna").css("width", $(window).width());
        $(".interna").css("top", parseFloat($(".info").css("height")));
      }
      if (root.Main.type === 4) {
        $(".interna").css("height", $(window).height() - parseFloat($(".info").css("height")));
        $(".interna").css("width", $(window).width());
        $(".interna").css("top", 0);
      }
      if (root.Main.type === "Mobile") {
        $(".interna").css("height", $(window).height() - parseFloat($("#header").css("height")));
        $(".interna").css("width", $(window).width());
        return $(".interna").css("top", parseFloat($("#header").css("height")));
      }
    };

    motionInternas = function() {
      var _opacity, _temp;
      _opacity = 1;
      _temp = 400;
      if (root.Main.type === "Mobile") {
        _opacity = 1;
      }
      $(".thumb_container").delay(0).animate({
        opacity: 0
      }, _temp, "easeInSine", function() {
        return $(this).remove();
      });
      $(".interna").delay(_temp).animate({
        opacity: _opacity
      }, _temp, "easeOutSine", function() {});
      if (root.Main.activeX) {
        animateArrows(".logoStrip", 72, 15);
        $(".logoStrip").delay(_temp).animate({
          left: -45
        }, _temp / 1.5, "easeOutSine", function() {});
        $(".hit_logo").css("width", 50);
      }
      return $(".hit_logo").on({
        click: function() {
          if (root.Main.pageCurrent !== "home") {
            root.Main.pageCurrent = "home";
            return motionReturnHome();
          }
        },
        mouseover: function() {
          if (root.Main.pageCurrent !== "home") {
            return $(this).css("cursor", "pointer");
          } else {
            return $(this).css("cursor", "default");
          }
        },
        mouseout: function() {}
      });
    };

    motionReturnHome = function() {
      var _temp;
      _temp = 400;
      animateArrows(".logoStrip", 72, 15);
      $(".logoStrip").delay(0).animate({
        left: 0
      }, _temp / 1.5, "easeOutSine");
      $(".interna").delay(_temp).animate({
        opacity: 0
      }, _temp, "easeInSine", function() {
        return $(this).remove();
      });
      return setTimeout((function() {
        return returnHomeEvent();
      }), 1000 * 0.2);
    };

    internaAjax = function() {
      var pagelink;
      activeLoader();
      pagelink = "include/internas/" + root.Main.pageCurrent.toString() + ".php";
      return $.ajax({
        url: pagelink,
        cache: false,
        success: function(page) {
          return root.Main.contentPage = page;
        },
        error: function(xhr) {
          root.Main.activeNav = true;
          return console.log("error de carregamento " + xhr);
        },
        complete: function() {
          var temp;
          temp = 0.2;
          return window.setTimeout((function() {
            return addContentPage();
          }), 1000 * temp);
        }
      });
    };

    addContentPage = function() {
      desactiveLoader();
      if (root.Main.pageCurrent === "about") {
        return contentAbout();
      } else {
        return contentInterna();
      }
    };

    contentAbout = function() {
      $(".interna").append(root.Main.contentPage);
      $(".about-content").css("position", "absolute");
      return $(".about-content").css("top", "25%");
    };

    contentInterna = function() {
      $(".interna").append("<div class=\"content\"></div>");
      $(".content").append(root.Main.contentPage);
      $(".content").css("opacity", 0);
      $(".interna .content .post-content .coluna2").css("opacity", 0);
      loaderImagem();
      $(".content").delay(0).animate({
        opacity: 1
      }, 1000, "linear", function() {});
      if (root.Main.type === 1 || root.Main.type === 2) {
        $(".content").css("width", 530);
        $(".content").css("margin-top", 30);
        $(".content").css("margin-left", -(parseFloat($(".content").css("width")) / 2));
        $(".coluna1 .titulo").css("width", 530);
        $(".coluna1 .descricao").css("width", 530);
      }
      if (root.Main.type === 3 || root.Main.type === 4 || root.Main.type === "Mobile") {
        $(".content").css("margin-left", -(parseFloat($(".content").css("width")) / 2) + 50);
        $(".coluna1").css("width", 370);
        $(".coluna1 .titulo").css("width", 350);
        $(".coluna1 .descricao").css("width", 350);
        if ($(window).height() < 650) {
          $(".content").css("margin-top", -5);
        }
      }
      if (root.Main.type === "Mobile") {
        $(".coluna2").append("<div class=\"tags\"></div>");
        $(".coluna2 .tags").append($(".coluna1 .tags").html());
        $(".coluna1").remove();
        $(".content").css("margin-left", -(parseFloat($(".coluna2").css("width")) / 2));
        $(".content").css("margin-top", -5);
      }
      return $(".content").each(function(index) {
        if (index > 0) {
          return $(this).remove();
        }
      });
    };

    loaderImagem = function() {
      $.loadImages($(".interna .content .post-content .coluna2 .post-img a img").attr("src"), function() {
        return $(".interna .content .post-content .coluna2").delay(1000 * 0.3).animate({
          opacity: 1
        }, 1000, "easeOutSine");
      });
      return setTimeout((function() {
        return $(".interna .content .post-content .coluna2").delay(0).animate({
          opacity: 1
        }, 1000, "easeOutSine");
      }), 1000 * 5);
    };

    activeLoader = function() {
      return $(".loader").css("display", "block");
    };

    desactiveLoader = function() {
      $(".loader").css("display", "none");
      return root.Main.activeNav = true;
    };

    resizeInternas = function() {
      if (root.Main.type === 1) {
        $(".interna").css("height", $(window).height());
        $(".interna").css("width", $(window).width() * root.Main.tamPocentagemRezise);
        $(".interna").css("left", root.Main.margemThumb);
      }
      if (root.Main.type === 2) {
        $(".interna").css("height", $(window).height());
        $(".interna").css("width", $(window).width() * root.Main.tamPocentagemRezise);
        $(".interna").css("left", $(window).width() * (1 - root.Main.tamPocentagemRezise) + 6);
      }
      if (root.Main.type === 3) {
        $(".interna").css("height", $(window).height() * root.Main.tamPocentagemRezise + 2);
        $(".interna").css("width", $(window).width());
        $(".interna").css("top", parseFloat($(".info").css("height")));
      }
      if (root.Main.type === 4) {
        $(".interna").css("height", $(window).height() - (parseFloat($(".info").css("height"))));
        $(".interna").css("width", $(window).width());
        return $(".interna").css("top", 0);
      }
    };

    animateArrows = function(target, amount, numFrames) {
      var incr, margin_top, moveImage, moveImageReturn, newPos;
      incr = amount;
      newPos = 0;
      margin_top = parseFloat($(target).css("marginTop"));
      if (root.Main.pageCurrent !== "home") {
        moveImage = function() {
          newPos -= incr;
          $(target).css("marginTop", margin_top + newPos);
          if (newPos > -(amount * numFrames)) {
            return setTimeout(moveImage, 30);
          }
        };
        return moveImage();
      } else {
        moveImageReturn = function() {
          newPos -= incr;
          $(target).css("marginTop", margin_top - newPos);
          if (newPos > -(amount * numFrames)) {
            return setTimeout(moveImageReturn, 30);
          }
        };
        return moveImageReturn();
      }
    };

    return Internas;

  })();

  Mobile = (function() {
    var animateArrows, callPage, clickThumb, createContainer, createHeader, createMobile, createThumb, createThumbContainer, cssHeader, cssReziseInternas, motionHeader, shareHeader;

    function Mobile(name) {
      this.name = name;
    }

    Mobile.prototype.init = function() {
      createMobile();
      createContainer();
      createHeader();
      cssHeader();
      motionHeader();
      shareHeader();
      return createThumbContainer();
    };

    callPage = function() {
      return root.Main.callPage();
    };

    Mobile.prototype.thumbResize = function() {
      return root.Main.thumb.init();
    };

    createMobile = function() {
      var loaded, myScroll;
      loaded = function() {
        var myScroll;
        return myScroll = new iScroll("wrapper");
      };
      myScroll = void 0;
      document.addEventListener("touchmove", (function(e) {
        return e.preventDefault();
      }), false);
      return setTimeout(loaded, 20);
    };

    createContainer = function() {
      $("body").append("<div id=\"header\"></div>");
      $("body").append("<div id=\"wrapper\"></div>");
      $("#wrapper").append("<div id=\"scroller\"></div>");
      return $("#scroller").append("<ul id=\"thelist\"></ul>");
    };

    createHeader = function() {
      $("#header").append("<div class=\"borda\"></div>");
      $("#header").append("<div class=\"logo\"></div>");
      $("#header .logo").append("<div class=\"logoStrip\"></div>");
      $("#header .logo .logoStrip").append("<img src=\"include/img/logo.png\" width=\"163\" height=\"2160\" alt=\"\" title=\"\" />");
      $("#header .logo").append("<div class=\"hit_logo\"></div>");
      $("#header").append("<div class=\"sobre\"></div>");
      $("#header").append("<div class=\"share\"></div>");
      $(".sobre").text(" Desenvolvedor de Interatividade: JavaScript / ActionScript ");
      $("#header .share").append("<div class=\"face\"></div>");
      $("#header .share").append("<div class=\"twitter\"></div>");
      $("#header .share").append("<div class=\"plus\"></div>");
      $("#header .sobre").css("opacity", 0.8);
      $("#header .share").css("opacity", 0.8);
      $("#header .logo .hit_logo").css("opacity", 0);
      if (!root.Main.ipod_active) {
        $("#header").append("<div class=\"btn_about\">ABOUT</div>");
        $("#header .btn_about").css("opacity", 1);
        return $("#header .btn_about").on({
          click: function() {
            if (root.Main.pageCurrent !== "about") {
              root.Main.pageCurrent = "about";
              return callPage();
            }
          },
          mouseover: function() {
            if (root.Main.pageCurrent !== "about") {
              return $(this).css("cursor", "pointer");
            }
          }
        });
      }
    };

    cssHeader = function() {
      $(".borda").css("height", 16);
      $(".borda").css("width", $(window).width());
      $(".borda").css("top", parseFloat($("#header").css("height")) - 16);
      $(".borda").css("background-image", "url(include/img/borda1.png)");
      $(".share").css("left", parseFloat($("#header").css("width")) - 100);
      $(".share").css("top", parseFloat($("#header").css("height")) - 90);
      $(".btn_about").css("padding-left", 5);
      $(".btn_about").css("padding-right", 30);
      $(".btn_about").css("left", parseFloat($("#header").css("width")) - 95);
      $(".btn_about").css("top", parseFloat($("#header ").css("height")) * 0.35);
      $(".logo").css("left", 5);
      $(".logo").css("top", 10);
      $(".sobre").css("top", parseFloat($(".logo").css("top")) + 8);
      $(".sobre").css("width", "60%");
      $(".sobre").css("left", -35);
      return $(".sobre").css("font-size", 12);
    };

    motionHeader = function() {
      return setTimeout((function() {
        if (root.Main.pageCurrent === 'home') {
          animateArrows(".logo .logoStrip", 72, 14);
        }
        return $(".logo").css("opacity", 0.5);
      }), 1000 * 0.3);
    };

    createThumbContainer = function() {
      var i, _results;
      $(".thumbClass").remove();
      i = 0;
      _results = [];
      while (i < root.Main.ntotal) {
        createThumb((root.Main.ntotal - 1) - i);
        _results.push(i++);
      }
      return _results;
    };

    createThumb = function(id) {
      var path_link;
      $("#thelist").append("<li id=\"containerHtml_thumb" + id + "\" class=\"thumbClass\"></li>");
      $("#containerHtml_thumb" + id).append("<div class=\"thumb\"></div>");
      $("#containerHtml_thumb" + id + " .thumb").append("<div class=\"thumbImagem\"></div>");
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem").append("<a target=\"_blank\"><img src=\"include/img/tumbID/" + root.Main.containersDeepLink[id + 3] + ".jpg\" width=\"555\" height=\"81\" alt=\"\" title=\"\" /><a>");
      path_link = root.Main.hrefLink[root.Main.containersDeepLink[id + 3]];
      if (root.Main.ipod_active) {
        $("#containerHtml_thumb" + id + " .thumb .thumbImagem a").attr("href", path_link);
      }
      root.Main.ratio = $(window).width() / 555.;
      $("#scroller li").css("height", 81 * root.Main.ratio);
      $("#containerHtml_thumb" + id).css("height", 81 * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb").css("height", 81 * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb").css("width", $(window).width());
      $("#containerHtml_thumb" + id + " .thumb").css("left", -10);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").width($("#containerHtml_thumb" + id + " .thumb .thumbImagem img").width() * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").height($("#containerHtml_thumb" + id + " .thumb .thumbImagem img").height() * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").css("opacity", 0.25);
      if (!root.Main.ipod_active) {
        $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").on({
          click: function(event) {
            event.preventDefault();
            return clickThumb($(this).parent().parent().parent().parent().attr("id"));
          }
        });
      }
      return $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").on({
        mouseover: function() {
          $(this).css("cursor", "pointer");
          return $(this).delay(0).animate({
            opacity: 0.6
          }, 200, "easeOutSine");
        },
        mouseout: function() {
          return $(this).delay(0).animate({
            opacity: 0.25
          }, 100, "easeInSine");
        }
      });
    };

    cssReziseInternas = function() {
      $(".interna").css("height", $(window).height());
      $(".interna").css("width", $(window).width());
      return $(".interna").css("top", parseFloat($("#header").css("height")));
    };

    clickThumb = function(id) {
      var filterId, number;
      filterId = new String(id).split("_thumb");
      number = filterId[1];
      root.Main.pageCurrent = root.Main.containersDeepLink[parseInt(number) + 3];
      return callPage();
    };

    $(window).bind("orientationchange", function(e) {
      cssHeader();
      createThumbContainer();
      if (!root.Main.ipod_active) {
        cssReziseInternas();
        return root.Main.interna.internasResize();
      }
    });

    /*	
    	$(window).bind "resize", (e) -> # MOBILE
    		cssHeader()
    		createThumbContainer() 
    		if( !root.Main.ipod_active ) ## Não tem no IPOD
    			cssReziseInternas() 
    			root.Main.interna.internasResize()
    */


    shareHeader = function() {
      $(".share .face").append($("#shareData #shareDataFace").html());
      $(".share .twitter").append($("#shareData #shareDataTwitter").html());
      return $(".share .plus").append($("#shareData #shareDataPlus").html());
    };

    animateArrows = function(target, amount, numFrames, _id) {
      var incr, moveImage, newPos, numCurrent;
      moveImage = function() {
        var _temp;
        newPos -= incr;
        $(target).css("marginTop", newPos);
        if (newPos > -(amount * numFrames)) {
          setTimeout(moveImage, 30);
        }
        numCurrent++;
        if (numFrames === numCurrent) {
          _temp = 500;
          $("#containerHtml_thumb" + _id + " .thumb .thumbStrip").delay(0).animate({
            opacity: 0.05
          }, _temp, "easeOutSine");
          return $("#containerHtml_thumb" + _id + " .thumb .thumbImagem img").delay(0).animate({
            opacity: 0.25
          }, _temp, "easeOutSine");
        }
      };
      incr = amount;
      newPos = 0;
      numCurrent = 0;
      return moveImage();
    };

    return Mobile;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Nav = (function() {
    var activeAbout, activeSetas, callPageInternasDepelink, createContainerSetas, createInternas, navDirecao, returnHome;

    function Nav(name) {
      this.name = name;
    }

    Nav.prototype.init = function() {
      root.Main.interna = new Internas("Internas");
      return root.Main.interna.init();
    };

    callPageInternasDepelink = function() {
      return root.Main.callDeepLink();
    };

    Nav.prototype.callNav = function(nav) {
      if (nav === "page") {
        createInternas();
        if (root.Main.pageCurrent !== "about" && root.Main.pageCurrent !== "home") {
          return createContainerSetas();
        }
      } else if (nav === "home") {
        if (root.Main.type !== "Mobile") {
          returnHome();
        }
        return activeAbout();
      } else {
        return activeAbout();
      }
    };

    createInternas = function() {
      activeAbout();
      if (root.Main.pageOld !== "about" && root.Main.pageOld !== "home" && root.Main.pageCurrent === "about") {
        return root.Main.interna.callInterna(false);
      } else {
        return root.Main.interna.callInterna(true);
      }
    };

    returnHome = function() {
      $(".thumb .thumbStrip").css("display", "none");
      $(".thumb .thumbImagem img").css("display", "none");
      root.Main.thumb.callThumb();
      if (root.Main.ie) {
        return $('body').bind('keydown');
      }
    };

    activeAbout = function() {
      callPageInternasDepelink();
      root.Main.pageArray.push(root.Main.pageCurrent);
      if (root.Main.pageArray.length > 1) {
        root.Main.pageOld = root.Main.pageArray[root.Main.pageArray.length - 2];
      }
      if (root.Main.pageCurrent === "about") {
        return $(".info .btn_about").delay(0).animate({
          opacity: 0
        }, 1000, "easeOutSine", function() {
          return $(this).css("display", "none");
        });
      } else {
        $(".info .btn_about").css("display", "block");
        return $(".info .btn_about").delay(0).animate({
          opacity: 1
        }, 1000, "easeOutSine");
      }
    };

    createContainerSetas = function() {
      var finalCoord, movTouch, nCurrent, ntotal, originalCoord, touch_end, touch_move, touch_start;
      ntotal = parseFloat(root.Main.ntotal);
      nCurrent = $.inArray(root.Main.pageCurrent, root.Main.containersDeepLink) - 3;
      $(".interna").append("<div class=\"setaEsq\"></div>");
      $(".interna").append("<div class=\"setaDir\"></div>");
      if (nCurrent === (ntotal - 1)) {
        activeSetas($(".setaEsq"), "desativar");
      } else {
        if (nCurrent === 0) {
          activeSetas($(".setaDir"), "desativar");
        }
      }
      $(".setaEsq,.setaDir").on({
        click: function() {
          return navDirecao($(this).attr("class"));
        },
        mouseover: function() {
          return $(this).css("cursor", "pointer");
        },
        mouseout: function() {}
      });
      $("body").focus();
      $("body").keydown(function(e) {
        e.preventDefault();
        if (e.which === 37) {
          navDirecao("setaEsq");
        } else {
          if (e.which === 39) {
            navDirecao("setaDir");
          }
        }
        return false;
      });
      if (root.Main.ie) {
        $('body').unbind('keydown');
      }
      if (!root.Main.mobile_active) {
        touch_start = function(event) {
          originalCoord.x = event.targetTouches[0].pageX;
          return originalCoord.y = event.targetTouches[0].pageY;
        };
        touch_move = function(event) {
          finalCoord.x = event.targetTouches[0].pageX;
          finalCoord.y = event.targetTouches[0].pageY;
          return event.preventDefault();
        };
        touch_end = function(event) {
          var changeX, changeY;
          changeY = originalCoord.y - finalCoord.y;
          changeX = originalCoord.x - finalCoord.x;
          if (changeY < movTouch.y && changeY > (movTouch.y * (-1))) {
            changeX = originalCoord.x - finalCoord.x;
            if (changeX > movTouch.x) {
              return navDirecao("setaDir");
            } else {
              if (changeX < (movTouch.x * (-1))) {
                return navDirecao("setaEsq");
              }
            }
          }
        };
        originalCoord = {
          x: 0,
          y: 0
        };
        finalCoord = {
          x: 0,
          y: 0
        };
        movTouch = {
          x: 30,
          y: 50
        };
        setTimeout(scrollTo, 0, 0, 1);
        document.addEventListener("touchstart", touch_start, false);
        document.addEventListener("touchmove", touch_move, false);
        return document.addEventListener("touchend", touch_end, false);
      }
    };

    navDirecao = function(dir) {
      var pageCurrentNumber;
      pageCurrentNumber = $.inArray(root.Main.pageCurrent, root.Main.containersDeepLink) - 3;
      if (root.Main.activeNav === true) {
        if (dir === "setaEsq") {
          if (pageCurrentNumber < (root.Main.ntotal - 1)) {
            root.Main.pageCurrent = root.Main.containersDeepLink[(pageCurrentNumber + 3) + 1];
            root.Main.interna.navControl();
            root.Main.activeNav = false;
            if ((pageCurrentNumber + 1) === (root.Main.ntotal - 1)) {
              activeSetas($(".setaEsq"), "desativar");
            } else {
              activeSetas($(".setaDir"), "ativar");
            }
          }
        } else {
          if (pageCurrentNumber > 0) {
            root.Main.pageCurrent = root.Main.containersDeepLink[(pageCurrentNumber + 3) - 1];
            root.Main.interna.navControl();
            root.Main.activeNav = false;
            if ((pageCurrentNumber - 1) === 0) {
              activeSetas($(".setaDir"), "desativar");
            } else {
              activeSetas($(".setaEsq"), "ativar");
            }
          }
        }
        return callPageInternasDepelink();
      }
    };

    activeSetas = function(_this, _type) {
      if (_type === "ativar") {
        _this.css("display", "block");
        return _this.delay(0).animate({
          opacity: 1
        }, 500, "easeOutSine", function() {});
      } else {
        return _this.delay(0).animate({
          opacity: 0
        }, 500, "easeInSine", function() {
          $(this).css("display", "none");
          return root.Main.activeNav = true;
        });
      }
    };

    return Nav;

  })();

  Thumb = (function() {
    var activeThumb, animateArrows, callPage, clickThumb, createContainerThumb, createThumb, motionInit, thumbTamanho, typeThumb;

    function Thumb(name) {
      this.name = name;
      root.Main.tamPocentagemRezise = root.Main.tamPocentagem;
      root.Main.activeScroll = true;
      createContainerThumb();
      typeThumb();
    }

    Thumb.prototype.motion = function() {
      var _temp;
      _temp = 0;
      if (root.Main.actibeThumbInit === true) {
        _temp = 2.2;
      } else {
        _temp = 0;
      }
      return window.setTimeout((function() {
        motionInit();
        return root.Main.actibeThumbInit = false;
      }), 1000 * _temp);
    };

    callPage = function() {
      return root.Main.callPage();
    };

    Thumb.prototype.callThumb = function() {
      root.Main.activeScroll = true;
      createContainerThumb();
      typeThumb();
      return root.Main.thumb.motion();
    };

    createContainerThumb = function() {
      $(".thumb_container").remove();
      $("body").append("<div class=\"thumb_container\"></div>");
      return $(".thumb_container").append("<div class=\"thumbsGroup\"></div>");
    };

    typeThumb = function() {
      var i, _results;
      if (root.Main.type === 1) {
        $(".thumb_container").css("height", $(window).height());
        $(".thumb_container").css("width", $(window).width() * root.Main.tamPocentagem);
        $(".thumb_container").css("left", root.Main.margemThumb);
      }
      if (root.Main.type === 2) {
        $(".thumb_container").css("height", $(window).height());
        $(".thumb_container").css("width", $(window).width() * root.Main.tamPocentagem - 5);
        $(".thumb_container").css("left", $(window).width() * (1 - root.Main.tamPocentagem) + 5);
      }
      if (root.Main.type === 3) {
        $(".thumb_container").css("height", $(window).height() - parseFloat($(".info").css("height")));
        $(".thumb_container").css("width", $(window).width());
        $(".thumb_container").css("top", parseFloat($(".info").css("height")));
        root.Main.tamPocentagem = 1;
      }
      if (root.Main.type === 4) {
        $(".thumb_container").css("height", $(window).height() - parseFloat($(".info").css("height")));
        $(".thumb_container").css("width", $(window).width());
        $(".thumb_container").css("top", 0);
        root.Main.tamPocentagem = 1;
      }
      i = 0;
      _results = [];
      while (i < root.Main.ntotal) {
        createThumb((root.Main.ntotal - 1) - i);
        thumbTamanho((root.Main.ntotal - 1) - i);
        _results.push(i++);
      }
      return _results;
    };

    motionInit = function() {
      if (root.Main.ie_old) {
        $(".thumb_container").css('display', "block");
      }
      return $(".mCSB_scrollTools").delay(0).animate({
        opacity: 1
      }, 1000 * 0.5, "linear", function() {
        var i, _results;
        i = 0;
        _results = [];
        while (i < root.Main.ntotal) {
          activeThumb((root.Main.ntotal - 1) - i);
          _results.push(i++);
        }
        return _results;
      });
    };

    createThumb = function(id) {
      $(".thumb_container .thumbsGroup").append("<div class=\"thumbClass\" id=\"containerHtml_thumb" + id + "\"></div>");
      $("#containerHtml_thumb" + id).append("<div class=\"thumb\"></div>");
      $("#containerHtml_thumb" + id + " .thumb").append("<div class=\"thumbStrip\"></div>");
      $("#containerHtml_thumb" + id + " .thumb .thumbStrip").append("<img src=\"include/img/thumb.png\" width=\"554\" height=\"1632\" alt=\"\" title=\"\" />");
      $("#containerHtml_thumb" + id + " .thumb").append("<div class=\"thumbImagem\"></div>");
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem").append("<img src=\"include/img/tumbID/" + root.Main.containersDeepLink[id + 3] + ".jpg\" width=\"554\" height=\"82\" alt=\"\" title=\"\" />");
      $("#containerHtml_thumb" + id + " .thumb .thumbStrip").css("opacity", 0.7);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").css("opacity", 0);
      return $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").css("display", "none");
    };

    thumbTamanho = function(id) {
      var heightThumb;
      $("#containerHtml_thumb" + id + " .thumb").css("width", $(window).width() * root.Main.tamPocentagem);
      root.Main.ratio = ($(window).width() / $("#containerHtml_thumb" + id + " .thumb .thumbStrip img").width()) * root.Main.tamPocentagem;
      $("#containerHtml_thumb" + id).css("top", (root.Main.topThumb * root.Main.ratio) * ((root.Main.ntotal - 1) - id));
      heightThumb = parseFloat($("#containerHtml_thumb" + id + " .thumb").css("height"));
      $("#containerHtml_thumb" + id + " .thumb").css("height", heightThumb * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb .thumbStrip img").width(($(window).width()) * root.Main.tamPocentagem);
      $("#containerHtml_thumb" + id + " .thumb .thumbStrip img").height($("#containerHtml_thumb" + id + " .thumb .thumbStrip img").height() * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").width($("#containerHtml_thumb" + id + " .thumb .thumbImagem img").width() * root.Main.ratio);
      $("#containerHtml_thumb" + id + " .thumb .thumbImagem img").height($("#containerHtml_thumb" + id + " .thumb .thumbImagem img").height() * root.Main.ratio);
      if (root.Main.activeScroll && id === 0) {
        $(".thumb_container").mCustomScrollbar({
          set_width: false,
          set_height: false,
          horizontalScroll: false,
          scrollInertia: 100,
          scrollEasing: "easeOutQuint",
          mouseWheel: "auto",
          autoDraggerLength: true,
          scrollButtons: {
            enable: true,
            scrollType: "continuous",
            scrollSpeed: 20,
            scrollAmount: 40
          },
          advanced: {
            updateOnBrowserResize: true,
            updateOnContentResize: true,
            autoExpandHorizontalScroll: true
          },
          callbacks: {
            onScroll: function() {},
            onTotalScroll: function() {},
            onTotalScrollOffset: 0
          }
        });
      }
      $(".thumb_container .thumbsGroup").css("height", 80 * root.Main.ratio * root.Main.ntotal);
      $(".thumb_container").mCustomScrollbar("update");
      if (root.Main.ie_old) {
        $(".thumb_container").css('display', "none");
      }
      return $(".mCSB_scrollTools").css("opacity", 0);
    };

    activeThumb = function(id) {
      return window.setTimeout((function() {
        var temp;
        temp = 400;
        return animateArrows("#containerHtml_thumb" + id + " .thumb .thumbStrip", 96 * root.Main.ratio, 15, id);
      }), 500 * ((root.Main.ntotal - 1) - id) / 2);
    };

    clickThumb = function(id) {
      var filterId, number;
      filterId = new String(id).split("_thumb");
      number = filterId[1];
      root.Main.pageCurrent = root.Main.containersDeepLink[parseInt(number) + 3];
      return callPage();
    };

    animateArrows = function(target, amount, numFrames, _id) {
      var incr, moveImage, newPos, numCurrent;
      moveImage = function() {
        var _temp;
        newPos -= incr;
        $(target).css("margin-top", newPos);
        if (newPos > -(amount * numFrames)) {
          setTimeout(moveImage, 30);
        }
        numCurrent++;
        if (numFrames === numCurrent) {
          _temp = 500;
          $("#containerHtml_thumb" + _id + " .thumb .thumbImagem img").css("display", "block");
          $("#containerHtml_thumb" + _id + " .thumb .thumbStrip").animate({
            opacity: 0.1
          }, _temp, "easeOutSine");
          return $("#containerHtml_thumb" + _id + " .thumb .thumbImagem img").delay(0).animate({
            opacity: 0.7
          }, _temp, "easeOutSine", function() {
            return $(this).on({
              click: function(event) {
                event.preventDefault();
                if (root.Main.activeNav === true) {
                  clickThumb($(this).parent().parent().parent().attr("id"));
                  root.Main.activeNav = false;
                }
                return false;
              },
              mouseover: function() {
                $(this).css("cursor", "pointer");
                return $(this).delay(0).animate({
                  opacity: 1
                }, _temp, "easeOutSine");
              },
              mouseout: function() {
                return $(this).delay(0).animate({
                  opacity: 0.7
                }, _temp - 100, "easeInSine");
              }
            });
          });
        }
      };
      incr = amount;
      newPos = 0;
      numCurrent = 0;
      return moveImage();
    };

    return Thumb;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  $(document).ready(function() {
    var main;
    root.Main = (function() {

      Main.ie = $.browser.msie;

      Main.ie_old = !Modernizr.canvas;

      Main.mobile_active = !(typeof window.ontouchstart !== "undefined" ? true : false);

      Main.ipod_active = (navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i));

      Main.random = function(min, max) {
        return min + Math.random() * (max - min);
      };

      Main.pageCurrent = 'home';

      Main.pageOld = "home";

      Main.pageArray = [];

      Main.topThumb = 80;

      Main.tamPocentagem = (Math.round(Main.random(7, 8))) / 10;

      Main.tamPocentagemRezise = 0;

      Main.type = Math.round(Main.random(1, 4));

      Main.margemThumb = -30;

      Main.ratio = 0;

      Main.contentPage = "";

      Main.activeX = true;

      Main.activeScroll = true;

      Main.activeNav = true;

      Main.actibeThumbInit = true;

      Main.indiceDeepLink = 1;

      Main.containersDeepLink = [];

      Main.containersDeepLink[Main.indiceDeepLink] = "home";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "about";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "espalhe";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "avell";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "2rios";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "morsa";

      Main.indiceDeepLink++;
	  Main.containersDeepLink[Main.indiceDeepLink] = "tag";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "intelectual";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "social";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "emocional";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "alimentar";

      Main.indiceDeepLink++;

      Main.containersDeepLink[Main.indiceDeepLink] = "fisica";

      Main.indiceDeepLink++;
	  
	  Main.containersDeepLink[Main.indiceDeepLink] = "alquimia";

      Main.indiceDeepLink++;
	 
	  Main.containersDeepLink[Main.indiceDeepLink] = "flappybird";

      Main.indiceDeepLink++; 
	  
	  Main.containersDeepLink[Main.indiceDeepLink] = "pacdroid";

      Main.indiceDeepLink++; 
	 
	  Main.containersDeepLink[Main.indiceDeepLink] = "vivojones3";

      Main.indiceDeepLink++;
	  
	  Main.containersDeepLink[Main.indiceDeepLink] = "vivojones2";

      Main.indiceDeepLink++;
	  
	  Main.containersDeepLink[Main.indiceDeepLink] = "vivojones1";

      Main.indiceDeepLink++;
	  
	  Main.containersDeepLink[Main.indiceDeepLink] = "androidbird";

      Main.indiceDeepLink++;

      Main.ntotal = Main.containersDeepLink.length - 3;

      Main.hrefLink = [];

      Main.hrefLink["espalhe"] = "https://sedexespalhe.com.br/";

      Main.hrefLink["avell"] = "http://nilocesar.eu/site/avell/";

      Main.hrefLink["2rios"] = "http://nilocesar.eu/site/2rios/";

      Main.hrefLink["morsa"] = "http://nilocesar.eu/site/morsa/";
	  
	  Main.hrefLink["tag"] = "http://taginterativa.com.br/";

      Main.hrefLink["intelectual"] = "http://nilocesar.eu/site/intelectual/";

      Main.hrefLink["social"] = "http://nilocesar.eu/site/social/";

      Main.hrefLink["emocional"] = "http://nilocesar.eu/site/emocional/";

      Main.hrefLink["alimentar"] = "http://nilocesar.eu/site/alimentar/";

      Main.hrefLink["fisica"] = "http://nilocesar.eu/site/fisica/";
	  
	  Main.hrefLink["alquimia"] = "http://nilocesar.eu/site/ALQUIMIA/";
	  
	  Main.hrefLink["flappybird"] = "http://nilocesar.eu/site/FLAPPYBIRD/";
	  
	  Main.hrefLink["pacdroid"] = "http://nilocesar.eu/site/PACDROID/";
	  
	  Main.hrefLink["vivojones1"] = "http://nilocesar.eu/site/VIVOJONES1/";
	  
	  Main.hrefLink["vivojones2"] = "http://nilocesar.eu/site/VIVOJONES2/";
	  
	  Main.hrefLink["vivojones3"] = "http://nilocesar.eu/site/VIVOJONES3/";
	  
	  Main.hrefLink["androidbird"] = "http://nilocesar.eu/site/ANDROIDBIRD/";

  

      Main.raiz = void 0;

      Main.info = void 0;

      Main.thumb = void 0;

      Main.nav = void 0;

      Main.interna = void 0;

      Main.deepLink = void 0;

      Main.mobile = void 0;

      function Main(name) {
        this.name = name;
        if ($(window).height() < 810) {
          root.Main.type = Math.round(root.Main.random(3, 4));
          $(".content").css("margin-top", -5);
          if ($(window).height() < 650) {
            root.Main.tamPocentagem = (Math.round(root.Main.random(7.4, 7.4))) / 10;
          }
        }
      }

      Main.prototype.init = function() {
        if (root.Main.mobile_active) {
          this.infoInit();
          this.thumbInit();
          this.navInit();
          return this.deepInit();
        } else {
          root.Main.type = "Mobile";
          this.mobileInit();
          this.navInit();
          return this.deepInit();
        }
      };

      $(window).load(function() {
        $(".loaderInit").remove();
        if (root.Main.mobile_active) {
          root.Main.resizeEvent();
          root.Main.info.motion();
          if (root.Main.pageCurrent === "home") {
            root.Main.thumb.motion();
          } else {

          }
          root.Main.actibeThumbInit = false;
        }
        if (!root.Main.ipod_active) {
          if (Modernizr.canvas) {
            root.Main.raiz = new Raiz("Raiz");
            return root.Main.raiz.init();
          } else {
            return $("#containerHtml_canvas").remove();
          }
        }
      });

      Main.prototype.infoInit = function() {
        return root.Main.info = new Info("Info");
      };

      Main.prototype.thumbInit = function() {
        return root.Main.thumb = new Thumb("Thumb");
      };

      Main.infoMotion = function() {
        return root.Main.info.init();
      };

      Main.prototype.navInit = function() {
        root.Main.nav = new Nav("Navegacao");
        return root.Main.nav.init();
      };

      Main.callPage = function(_page) {
        if (_page == null) {
          _page = "page";
        }
        root.Main.nav.callNav(_page);
        return this.callDeepLink();
      };

      Main.prototype.deepInit = function() {
        root.Main.deepLink = new Deeplink("Deeplink");
        return root.Main.deepLink.init();
      };

      Main.callDeepLink = function() {
        var indexPage;
        indexPage = $.inArray(root.Main.pageCurrent, this.containersDeepLink);
        return root.Main.deepLink.chageHash(indexPage);
      };

      Main.prototype.mobileInit = function() {
        root.Main.mobile = new Mobile("Mobile");
        return root.Main.mobile.init();
      };

      Main.resizeEvent = function() {
        var completeResize;
        $(window).resize(function(e) {
          root.Main.tamPocentagem = root.Main.tamPocentagemRezise;
          root.Main.info.infoResize();
          if (root.Main.pageCurrent === "home") {
            $(".thumb .thumbStrip").css("display", "none");
            $(".thumb .thumbImagem img").css("display", "none");
            $('.thumb_container').remove();
          }
          return completeResize((function() {
            if (root.Main.pageCurrent === "home") {
              return root.Main.thumb.callThumb();
            } else {
              return root.Main.interna.internasResize();
            }
          }), 500);
        });
        return completeResize = (function() {
          var timer;
          timer = 0;
          return function(callback, ms) {
            clearTimeout(timer);
            return timer = setTimeout(callback, ms);
          };
        })();
      };

      return Main;

    })();
    main = new root.Main();
    return main.init();
  });

}).call(this);
